############################################################################
#
# This file is generated by RT-Druid.
# Please do not modify it.
#
############################################################################

# ###*B*###
#
# ERIKA Enterprise - a tiny RTOS for small microcontrollers
# 
# Copyright (C) 2002-2018 Evidence Srl
# 
# This file is part of ERIKA Enterprise.
# 
# See LICENSE file.
#
# ###*E*###

############################################################################
#
# Repository Inclusion
#
############################################################################

$(info ***************************)
$(info * Pulling erika files from:)
$(info ***************************)
$(info * ERIKA_FILES=$(ERIKA_FILES))
include $(ERIKA_FILES)/mk/ee_pull.mk


############################################################################
#
# End
#
############################################################################

